repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.5.0
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@8.5.0
          - eslint-plugin-import@2.25.3
          - eslint-import-resolver-typescript@2.5.0
          - eslint-plugin-react@7.27.1
          - eslint-plugin-react-hooks@4.3.0
          - eslint-webpack-plugin@3.1.1
          - typescript-eslint@0.0.1-alpha.0
          - "@typescript-eslint/eslint-plugin@5.7.0"
          - "@typescript-eslint/parser@5.7.0"
        files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
        types: [file]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 21.11b1
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910-1
    hooks:
      - id: mypy
        additional_dependencies:
          - types-requests
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear~=21.9.2
          - pep8-naming~=0.12.1
