ALTER TABLE lipas.abstract ADD COLUMN deleted boolean NOT NULL DEFAULT false;
ALTER TABLE kooste.lipas_pisteet ADD COLUMN deleted boolean NOT NULL DEFAULT false;
ALTER TABLE kooste.lipas_viivat ADD COLUMN deleted boolean NOT NULL DEFAULT false;
ALTER TABLE kooste.osm_pisteet ADD COLUMN deleted boolean NOT NULL DEFAULT false;
ALTER TABLE kooste.osm_alueet ADD COLUMN deleted boolean NOT NULL DEFAULT false;
ALTER TABLE kooste.tamperewfs_luonnonmuistomerkit ADD COLUMN deleted boolean NOT NULL DEFAULT false;
ALTER TABLE kooste.tamperewfs_luontopolkurastit ADD COLUMN deleted boolean NOT NULL DEFAULT false;
ALTER TABLE kooste.tamperewfs_luontopolkureitit ADD COLUMN deleted boolean NOT NULL DEFAULT false;
ALTER TABLE kooste.museovirastoarcrest_rkykohteet ADD COLUMN deleted boolean NOT NULL DEFAULT false;
ALTER TABLE kooste.museovirastoarcrest_muinaisjaannokset ADD COLUMN deleted boolean NOT NULL DEFAULT false;
ALTER TABLE kooste.syke_natura2000 ADD COLUMN deleted boolean NOT NULL DEFAULT false;
ALTER TABLE kooste.syke_valtionluonnonsuojelualueet ADD COLUMN deleted boolean NOT NULL DEFAULT false;
CREATE INDEX ON kooste.lipas_pisteet (deleted);
CREATE INDEX ON kooste.lipas_viivat (deleted);
CREATE INDEX ON kooste.osm_pisteet (deleted);
CREATE INDEX ON kooste.osm_alueet (deleted);
CREATE INDEX ON kooste.tamperewfs_luonnonmuistomerkit (deleted);
CREATE INDEX ON kooste.tamperewfs_luontopolkurastit (deleted);
CREATE INDEX ON kooste.tamperewfs_luontopolkureitit (deleted);
CREATE INDEX ON kooste.museovirastoarcrest_rkykohteet (deleted);
CREATE INDEX ON kooste.museovirastoarcrest_muinaisjaannokset (deleted);
CREATE INDEX ON kooste.syke_natura2000 (deleted);
CREATE INDEX ON kooste.syke_valtionluonnonsuojelualueet (deleted);
