name: Deploy
on:
  push:
    branches: [main, 21_lipas-populating] # TODO: remove branch

jobs:
  build-and-deploy-web-app:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Install
        run: yarn
      - name: Build
        run: yarn run build
        env:
          API_KEY_NLS: ${{ secrets.API_KEY_NLS }}
          TILESERVER_URL: ${{ secrets.TILESERVER_URL }}
      - name: Deploy app build to S3 bucket
        run: aws s3 sync ./dist/ s3://${{ secrets.AWS_BUCKET_NAME }} --delete

  build-lambda-functions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Build zip files for lambda
        run: make build-lambda
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_LAMBDA_UPLOAD_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_LAMBDA_UPLOAD_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Update lambda functions
        run: make update-lambda -C infra
